### PR TITLE
Use a bound constraint for PHPUnit and allow Symfony 3

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Comment by aik099** [comment]
Merging, thanks @stof .

**Comment by aik099** [comment]
I'm not sure, why GitHub says that merge happened into `minkphp:master` branch, because the branch actually is `minkphp/phpunit-mink:master`.

**Comment by stof** [comment]
@aik099 it displays branch names as owner:branch because it is always in the network of forks of this repo (you cannot send a PR from a repo which is not a fork)

**Comment by stof** [comment]
@aik099 you may want to check the scrutinizer issues though

**Comment by aik099** [comment]
> @aik099 you may want to check the scrutinizer issues though

Will do.

**Comment by aik099** [comment]
PR solving all Scrutinizer CI reported issue created: #80

**Pull request merged**
