### PR TITLE
Don't run SauceLabs tests, when no API credentials are specified

### LINKED ISSUE #18: Skip SauceLabs tests for Pull Requests
We've using encrypted env variables for pass SauceLabs access credentials in `.travis.yml` file. For security reasons Travis doesn't decrypt those for Pull Requests (see http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables).

We should check, that if we're building on Travis + this is Pull Request (TRAVIS_SECURE_ENV_VARS or TRAVIS_PULL_REQUEST), then skip these tests.

### PR DESCRIPTION
**Pull request by aik099**
I've also identified and fixed an issue, when event listener in test was using wrong priority and resulted in test to always fail.

Closes #18

### CODE REVIEW

**Comment by aik099** [comment]
At last all tests are passing.

Two types of Travis CI errors were fixed with this PR:

1. no connection to SauceLabs was made when we're attempted to make a connection with empty credentials (message was `The Selenium Server is not active on host ...@ondemand.saucelabs.com at port 80`)
2. attempt to post job status to SauceLabs failed due wrong SSL certificate usage (message was `PHP Fatal error:  Uncaught exception 'WebDriver\Exception\CurlExec' with message 'Curl error thrown for http PUT to https://saucelabs.com/rest/v1//jobs/session with params: {"passed":true}`)

It turned out that connection to SauceLabs was initiated by mistake due #35 bug.

**Comment by aik099** [comment]
Now contributors can run test suite locally without specifying SauceLabs credentials and relevant tests would just be skipped. Before this was causing errors, similar to ones seen on Travis CI. When I was single contributor to library fact, that somebody running test suite might not have any SauceLabs credentials specified wasn't very obvious to me.

**Comment by aik099** [comment]
Even though SauceLabs-related tests aren't executed on PR, but they will be executed on merges and direct pushes.

**Comment by stof** [comment]
:+1:

**Comment by stof** [comment]
@aik099 what about disabling the PHPCS run on Scrutinizer for now (until they support PHPCS 2), so that we can get all the other Scrutinizer benefits (static analysis of the code for instance) ? Currently, it reports only broken run.

**Comment by aik099** [comment]
> until they support PHPCS 2

Seems that @schmittjoh is quite busy right now to enable it, which renders all PHP_CodeSniffer 2.0-based standards useless.

> Currently, it reports only broken run.

I'll that now and re-run the inspection.

**Comment by aik099** [comment]
Done.

**Comment by aik099** [comment]
@stof , I'll think I'll merge all PR's I've made yesterday tomorrow evening to give you some time for review and ask @Vinai to rebase his PR on top of `master` for his Travis CI build to pass as well.

**Comment by stof** [comment]
@aik099 I already validated this one. You can merge it

**Pull request merged**
