### PR TITLE
Add testing on PHP 7

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Comment by stof** [comment]
OK, the code is actually not compatible with PHPUnit 5

**Comment by aik099** [comment]
The failing test about wrong `onNotSuccessfulTest` method declaration should be fixed as part of #77, not no PR was sent in 20 days since issue was reported. If that is fixed, then maybe PHP 7 build will be fixed.

**Comment by stof** [comment]
There are other issues with PHPUnit 5 (see an issue about a mocked method not being there).

What do you think about merging this PR after adding it as an allowed_failure ? this would allow having a CI build showing the PHPunit 5 compat. This would be easier when someone sends a PR as we will have the build showing improvements.
If you agree, I will update the PR to add the config for allowed failures

**Comment by aik099** [comment]
So for other Mink-related repos we're removing `allow_failures` for PHP 7, but for this one we're doing the opposite for the time being to be able to slowly solve PHP 7 issues until it will work fine and then remove it from `allow_failures`?

**Comment by stof** [comment]
@aik099 we are removing allow_failures when the code is compatible already. Here, the idea is to run the CI with failure allowed to see the progress towards support instead of not seeing at all whether we are ready (and yes, we should disallow failures once PHPUnit 5 is properly supported)

**Comment by aik099** [comment]
OK. Then please do as you've recommended.

**Comment by stof** [comment]
updated

**Comment by aik099** [comment]
Build passed. I guess it's ready to be merged then.

**Comment by aik099** [comment]
Merging, thanks @stof .

**Pull request merged**
